/* LOGIN */
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

/* LOGOUT */
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

/* REGISTER */
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

/* VALIDATE */
export const VALIDATE = "VALIDATE";
export const VALIDATE_SUCCESS = "VALIDATE_SUCCESS";
export const VALIDATE_FAILURE = "VALIDATE_FAILURE";

/* REGISTER_PASS */
export const REGISTER_PASS = "REGISTER_PASS";
export const REGISTER_PASS_SUCCESS = "REGISTER_PASS_SUCCESS";
export const REGISTER_PASS_FAILURE = "REGISTER_PASS_FAILURE";

/* FORGOT_PASS */
export const FORGOT_PASS = "FORGOT_PASS";
export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAILURE = "FORGOT_PASS_FAILURE";

/* VALIDATE_PASS */
export const VALIDATE_PASS = "VALIDATE_PASS";
export const VALIDATE_PASS_SUCCESS = "VALIDATE_PASS_SUCCESS";
export const VALIDATE_PASS_FAILURE = "VALIDATE_PASS_FAILURE";

/* NEW_PASS */
export const NEW_PASS = "NEW_PASS";
export const NEW_PASS_SUCCESS = "NEW_PASS_SUCCESS";
export const NEW_PASS_FAILURE = "NEW_PASS_FAILURE";